notifications:
  email: false
language: node_js
node_js:
  - stable
services:
  - mongodb
install:
  - npm install --save cors
  - npm install -g codecov
before_script:
  - npm install -g jest-cli
script:
  - npm run security-check
