notifications:
  email: false
language: node_js
node_js:
  - 8.9.4
services:
  - mongodb
install:
  - npm install --save cors
  - npm install -g codecov
before_script:
  - npm install -g jest-cli
script:
  - jest test --ci --colors && codecov
  - npm run security-check
