version: '3'

services:
  postgres:
    image: postgres:10.1-alpine
    container_name: postgres
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
