version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_api
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elastic_search
    ports:
     - "9200:9200"
